apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: yara-scan-pipeline
spec:
  tasks:
  - name: yara-task
    taskRef:
        name: yara-task
    params:
      - name: image-digest
        value: sha256:9c810eccada0cc6f25b46eeeea4516bab01828faef4fdd2fe49c760518b90dd1
      - name: image-url
        value: registry.access.redhat.com/ubi9/ubi-minimal

    

        